name: Main Workflow
on: [push]
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Which chromium
        shell: bash
        run: which chromium
      - name: view usr bin
        shell: bash
        run: ls -la /usr/bin
      - name: Install Chromium
        shell: bash
        run: sudo snap install chromium
      - name: Which chromium
        shell: bash
        run: which chromium
      - name: view usr bin
        shell: bash
        run: ls -la /usr/bin
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: test.js
